# Generated by Django 6.0.2 on 2026-02-28 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manyimages",
            old_name="product",
            new_name="product_variant",
        ),
        migrations.AddField(
            model_name="manyimages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manyimages",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
        ),
        migrations.AddField(
            model_name="manyimages",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
        ),
    ]
