# Generated by Django 6.0.2 on 2026-02-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0002_rename_product_manyimages_product_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                to="product_module.category", verbose_name="دسته بندی محصول"
            ),
        ),
    ]
