# Generated by Django 6.0.2 on 2026-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0003_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default=1, upload_to="category/image"),
            preserve_default=False,
        ),
    ]
