# Generated by Django 6.0.2 on 2026-03-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0004_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="images",
        ),
        migrations.AlterField(
            model_name="manyimages",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_images",
                to="product_module.product",
            ),
        ),
    ]
