# Generated by Django 6.0.2 on 2026-03-02 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0005_remove_productvariant_images_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manyimages",
            old_name="product_variant",
            new_name="product",
        ),
    ]
