# Generated by Django 6.0.2 on 2026-03-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0006_rename_product_variant_manyimages_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(default=1, upload_to="brand/image"),
            preserve_default=False,
        ),
    ]
