# Generated by Django 6.0.2 on 2026-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0007_brand_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products_category",
                to="product_module.category",
                verbose_name="دسته بندی محصول",
            ),
        ),
    ]
