# Generated by Django 6.0.2 on 2026-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0008_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="sales_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="تعداد به فروش رفته"
            ),
        ),
    ]
