# Generated by Django 6.0.2 on 2026-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0009_productvariant_sales_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sales_count",
            field=models.IntegerField(default=0, verbose_name="تعداد به فروش رفته"),
        ),
    ]
