# Generated by Django 6.0.2 on 2026-05-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0010_alter_productvariant_sales_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manyimages",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="product_module.product",
            ),
        ),
    ]
