# Generated by Django 6.0.5 on 2026-05-13 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0011_alter_manyimages_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_category",
                to="product_module.category",
                verbose_name="دسته بندی محصول",
            ),
        ),
    ]
