# Generated by Django 6.0.2 on 2026-05-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0012_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_brand",
                to="product_module.brand",
                verbose_name="برند محصول",
            ),
        ),
    ]
