# Generated by Django 6.0.2 on 2026-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="عنوان")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=500, upload_to="", verbose_name="عکس"),
                ),
                (
                    "text_in_btn",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="متن داخل دکمه"
                    ),
                ),
                ("url_btn", models.URLField(max_length=600, verbose_name="url دکمه")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
            ],
        ),
    ]
