# Generated by Django 6.0.2 on 2026-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_setting_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baner",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to="baner/image", verbose_name="عکس"
            ),
        ),
    ]
