# Generated by Django 6.0.2 on 2026-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_setting_module", "0002_alter_baner_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "text_in_btn",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن داخل دکمه"
                    ),
                ),
                ("url_btn", models.URLField(max_length=600, verbose_name="url دکمه")),
                (
                    "where",
                    models.CharField(
                        choices=[("top", "top"), ("buttom", "buttom")], max_length=10
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
            ],
        ),
    ]
