# Generated by Django 6.0.2 on 2026-05-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_setting_module", "0003_elan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
            ],
        ),
    ]
