# Generated by Django 6.0.2 on 2026-05-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_setting_module", "0004_settingsite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsite",
            name="logo",
            field=models.ImageField(upload_to="logo/image"),
        ),
    ]
