# Generated by Django 6.0.2 on 2026-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_setting_module", "0005_alter_settingsite_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsite",
            name="name",
            field=models.CharField(default="", verbose_name="نام سایت"),
        ),
        migrations.AlterField(
            model_name="settingsite",
            name="logo",
            field=models.ImageField(upload_to="logo/image", verbose_name="لوگو سایت"),
        ),
    ]
