# Generated by Django 6.0.2 on 2026-03-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_module", "0006_rename_product_variant_manyimages_product"),
        ("products_like_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likesproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.product",
                unique=True,
                verbose_name="محصول",
            ),
        ),
    ]
