# Generated by Django 6.0.2 on 2026-03-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0006_rename_product_variant_manyimages_product"),
        ("products_like_module", "0002_alter_likesproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likesproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_like",
                to="product_module.product",
                verbose_name="محصول",
            ),
        ),
    ]
