# Generated by Django 6.0.2 on 2026-04-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0010_alter_productvariant_sales_count"),
        ("products_like_module", "0004_alter_likesproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likesproduct",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_like",
                to="product_module.product",
                verbose_name="محصول",
            ),
        ),
    ]
