# Generated by Django 6.0.2 on 2026-04-04 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
        ),
    ]
