# Generated by Django 6.0.2 on 2026-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0002_orderitem_created_at_orderitem_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cart", "cart"),
                    ("paid", "paid"),
                    ("cancelled", "cancelled"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("completed", "completed"),
                    ("returned", "returned"),
                ],
                default="cart",
                max_length=150,
            ),
        ),
    ]
