# Generated by Django 6.0.2 on 2026-04-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rahgiri_code",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="کد رهگیری پرداخت سفارش",
            ),
        ),
    ]
