# Generated by Django 6.0.2 on 2026-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0004_order_rahgiri_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="آدرس تحویل گیرنده"
            ),
        ),
    ]
