# Generated by Django 6.0.2 on 2026-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_module", "0007_discountcode_userdiscountusage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdiscountusage",
            name="discount_amount_applied",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="مبلغ تخفیف اعمال شده",
            ),
        ),
    ]
