# Generated by Django 6.0.2 on 2026-05-07 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_module", "0008_alter_userdiscountusage_discount_amount_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcode",
            name="percent",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="درصد تخفیف",
            ),
        ),
    ]
