# Generated by Django 6.0.5 on 2026-05-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_module", "0009_alter_discountcode_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountcode",
            name="amount",
        ),
    ]
