# Generated by Django 6.0.5 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0010_remove_discountcode_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_pan",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="شماره کارت پرداخت شده",
            ),
        ),
    ]
