# Generated by Django 6.0.5 on 2026-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0011_order_card_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("cart", "cart"),
                    ("pending", "pending"),
                    ("paid", "paid"),
                    ("cancelled", "cancelled"),
                    ("processing", "processing"),
                    ("shipped", "shipped"),
                    ("completed", "completed"),
                    ("returned", "returned"),
                ],
                default="cart",
                max_length=150,
            ),
        ),
    ]
