# Generated by Django 6.0.5 on 2026-06-10 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart_module", "0012_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
    ]
