# Generated by Django 6.0.2 on 2026-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                ("email", models.CharField(max_length=255, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=255, verbose_name="موصوغ")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
                (
                    "is_read_by_admin",
                    models.BooleanField(
                        default=False, verbose_name="خوانده شده توسط ادمین"
                    ),
                ),
            ],
        ),
    ]
