# Generated by Django 6.0.2 on 2026-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام موضوع")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="توصیحاتی در باره موضوع",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین آپدیت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
            ],
        ),
    ]
