# Generated by Django 6.0.2 on 2026-04-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment_module", "0002_comment_rating"),
        ("product_module", "0008_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="product_module.product",
                verbose_name="محصول",
            ),
        ),
    ]
