# Generated by Django 6.0.2 on 2026-02-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(
                blank=True,
                default="ZT3lMCsiXdTXMEIYE4IKjBloGsdqt8MSJOYK3OcTTGtQYlL4eqYFv7lLfwszQIzSjoS3p9flpN1BBwnyexjtZV02WPDuOjdOgeBwcymZupFe4rOuZYYOm5GQVXRi7K",
                max_length=126,
                null=True,
            ),
        ),
    ]
