# Generated by Django 6.0.2 on 2026-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_module", "0002_user_email_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_active_code",
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
